# Generated by Django 3.1.3 on 2020-12-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_pub',
            new_name='date_pub',
        ),
    ]
