# Generated by Django 3.1.4 on 2020-12-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20201223_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='data_pub',
            new_name='date_pub',
        ),
    ]
