# Generated by Django 3.1.4 on 2021-01-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_auto_20201224_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=50)),
                ('file', models.FilePathField(match='*.mp3', path='media/mp3')),
            ],
        ),
    ]
